#!/usr/bin/env python3
#
# Copyright (c) 2021, AT&T Intellectual Property. All rights reserved.
# SPDX-License-Identifier: GPL-2.0-only
#

"""
Sends a VCI notification that reports a LAG membership change.
"""

import sys
import argparse
import vci

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Sends a VCI notification to report a LAG membership change.')
    parser.add_argument('bond_group', help='Bonding group name')
    parser.add_argument('member_interface', help='Member interface name')
    parser.add_argument('operation', help='Membership change operation',
        choices=['add', 'del'])

    args = parser.parse_args()

    if args.operation == 'add':
        operation_add = 'true'
    else:
        operation_add = 'false'

    notification = {
        'vyatta-interfaces-bonding-v1:bond-group': args.bond_group,
        'vyatta-interfaces-bonding-v1:member-interface': args.member_interface,
        'vyatta-interfaces-bonding-v1:operation-add': operation_add
    }

    client = vci.Client()
    client.emit('vyatta-interfaces-bonding-v1', 'bond-membership-update',
        notification)

    sys.exit(0)
